name: Generate static site

on:
  push:
    branches:
      - master
  schedule:
    - cron: '12 10 * * */3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build site
        run: |
            make
            tree

      - name: Generate artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: .

      - name: Deploy
        run: |
          mkdir ~/.ssh
          cat ${{ secrets.SSH_KEY }} >~/.ssh/id_rsa
          cat ${{ secrets.HOST_KEY }} >~/.ssh/known_hosts
          cat >~/.ssh/config <<EOF
          Host deploy
            Hostname ${{ secrets.HOST_NAME }}
            User ${{ secrets.HOST_USER }}
            IdentityFile ~/.ssh/id_rsa
          EOF
          rsync --exclude '*~' --exclude Makefile --exclude .git --exclude .gitignore --exclude .DS_Store -Carv . deploy:
