name: Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: '12 10 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build site
        run: |
            make
            tree

      - name: Deploy
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/id_rsa ~/.ssh/known_hosts ~/.ssh/config
          chmod 600 ~/.ssh/*
          echo "${{ secrets.SSH_KEY }}" >~/.ssh/id_rsa
          echo "${{ secrets.HOST_KEY }}" >~/.ssh/known_hosts
          cat >~/.ssh/config <<EOF
          Host deploy
            Hostname ${{ secrets.HOST_NAME }}
            User ${{ secrets.HOST_USER }}
            IdentityFile ~/.ssh/id_rsa
          EOF
          rsync --exclude '*~' --exclude Makefile --exclude .git --exclude .ssh --exclude .gitignore --exclude .DS_Store -Carv . deploy:
